[workspace]
members = ["engine", "server", "conversion", "visualization", "utils", "catchup", "cooperative", "chpot"]
resolver = "2"

[profile.dev]
opt-level = 3
[profile.release]
debug = true
incremental = false
codegen-units = 1
